### ISSUE TITLE
Introduce configuration file

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#253]
As pointed out in the comment in #140, and referenced in #153, it is becoming necessary to introduce a configuration file.
There has been a few attempts at it, using different techniques and libraries and I want to collate these efforts in one.

The configuration file shall use the ConfigParser format and there should be a unified config parser class as it is done in Cuckoo.

**Comment by deralexxx** [comment]
do you wanna introduce it or shall I make a global ConfigParser available? (I would basically use the stuff I wrote for the cuckoo module and place it to the main module so that not every module has to import ConfigParser etc and would introduce the config params shown in #140

**Comment by botherder** [comment]
I will take care of the config file. As it is quite a core change, I want to make sure I give it some thought and lay out a good structure.

**Comment by kevthehermit** [comment]
Started work on this. Uses ConfigParser. Lifted a big chunk from Cuckoo. 

https://github.com/kevthehermit/viper/tree/config_parser

Also did some work on making it DB agnostic. This involved some minor changes giving tables a prefix. This means i can store multiple projects in a single DB. 

SQLite still stores individual projects in separate viper.db files. 

Tested with Sqlite, MySQl and Postgress. 

https://github.com/kevthehermit/viper/tree/config_parser

Modifed a couple of the modules to use the Config class. 

At the moment i am using a single [modules] section rather than having individual sectiosn for each module. But this is a simple change its jsut a metter of prefernece. 

Still needs some testing and adjusting but working so far. 

Thoughts?

**Comment by kevthehermit** [comment]
Merge conflicts since i first created this. 

Now has a pull - https://github.com/viper-framework/viper/pull/336

**Comment by kevthehermit** [comment]
Any thoughts on this?
