### ISSUE TITLE
Last Tag version is 3 Year Old :) 

### ISSUE THREAD

**Issue by Th4nat0s** [viper-framework/viper#612]
Some people like stable release even if it's not the last one.

Is it possible ( beer offer for that still possible ) to tag a more or less "stable" version ?

**Comment by Rafiot** [comment]
Riight, I think we can call the current release 3.0, @frennkie @botherder what do you think?

**Comment by frennkie** [comment]
I'm fine with creating a release, although we should to think about whether to call it 1.3, 1.4, 2.0 or 3.0.. :-)
If we change the major number, then - IMHO - we should check the roadmap and see what should go in (and also what will be removed/replaced - e.g. the API).

**Comment by frennkie** [comment]
I thought a bit about this and I agree that there are people that prefer downloading/installing _releases_. I think we could work on providing packages that can be installed with `pip` (maybe directly from PyPI).

I started working on this in #614 in which I moved the Yara rules to the storage path and updated the setup.py script.

**Comment by frennkie** [comment]
I think we should move forward by creating a `1.4` release tag and branch that reflects the current state of `master` and then starting the work on a version `2.0`. Some of the reported issue are best fixed by doing (breaking) changes and threrefore changing the major version makes sense (to me).
Having a stable `1.4` version would be helpful for people that are using Viper but are currently unable to handle changes (e. g. in API).

I would
* [ ] identify PRs that can and should go into `1.4` (although I currently don't see any)
* [ ] identify bugs that must be fixes for a `1.4` release
* [ ] create a release branch (e.g. `rel-1.4`or `rel-1.4.x`)
* [ ] clearly highlight / warn on deprecations (e.g. the unmaintained bottle web interface)
* [ ] update docs
* [ ] bump version to `1.4.0`
* [ ] push release tag `1.4.0`

Then on master we would change the version to `2.0.dev[0]` and get some of the PRs and Issues fixed for a eventual final `2.0.0` release.

@botherder What do think about this?

**Comment by Th4nat0s** [comment]
Yes @botherder is it ok ? :)

**Comment by botherder** [comment]
As the web interface is now replaced to Django, we're closing the 1.x branch release with 1.3 that I just pushed out and we move on to a 2.x now.
